# Generated by Django 3.2.7 on 2021-11-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_anonymuscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymusComment',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length='200')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
