# Generated by Django 3.2.7 on 2021-12-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymus', '0004_alter_anonymuscomment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymusComment',
        ),
    ]
