# Generated by Django 3.2.7 on 2021-09-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('date_birth', models.DateField(max_length=8)),
                ('bio', models.TextField(max_length=140)),
                ('ava', models.ImageField(blank=True, null=True, upload_to='media/avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('text', models.TextField(verbose_name='text')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Art'), (2, 'business'), (3, 'science ')], verbose_name='category')),
                ('autor', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
